#!/bin/bash

# Instructions for setting up the Supabase database

echo "=== Supabase Database Setup Instructions ==="
echo ""
echo "To create the necessary tables in your Supabase database, follow these steps:"
echo ""
echo "1. Go to your Supabase dashboard: https://app.supabase.com/"
echo "2. Select your project: 'iPhone URL Sharing'"
echo "3. Navigate to the 'SQL Editor' section"
echo "4. Create a new query"
echo "5. Copy and paste the SQL from the create_tables.sql file"
echo "6. Click 'Run' to execute the SQL"
echo ""
echo "This will create the 'urls' table with the necessary columns and security policies."
echo ""
echo "Alternatively, you can use the Table Editor in the Supabase dashboard to create the table:"
echo "1. Go to the 'Table Editor' section"
echo "2. Click 'New Table'"
echo "3. Set the table name to 'urls'"
echo "4. Add the following columns:"
echo "   - id: UUID (primary key, default: gen_random_uuid())"
echo "   - url: TEXT (not null)"
echo "   - page_title: TEXT"
echo "   - tags: TEXT[] (default: '{}')"
echo "   - date_accessed: TIMESTAMP WITH TIME ZONE (default: now())"
echo "   - user_id: TEXT (not null)"
echo "   - summary: TEXT"
echo "   - created_at: TIMESTAMP WITH TIME ZONE (default: now())"
echo "   - updated_at: TIMESTAMP WITH TIME ZONE (default: now())"
echo "5. Enable Row Level Security (RLS)"
echo "6. Click 'Save'"
echo ""
echo "After creating the table, set up the RLS policies to secure your data:"
echo "1. Go to the 'Authentication' section"
echo "2. Click on 'Policies'"
echo "3. Find the 'urls' table and click 'New Policy'"
echo "4. Create policies for SELECT, INSERT, UPDATE, and DELETE operations"
echo "   that check if auth.uid()::text = user_id"
echo ""
echo "=== End of Instructions ===" 